### ISSUE TITLE
Missing tracks 

### ISSUE THREAD

**Issue by dazld** [enoughrec/arecordlabel#45]
http://enoughrecords.scene.org/release/enrcmp01

seems to have no tracks available..?

**Comment by psenough** [comment]
yeah, there is already a ticket for that https://github.com/enoughrec/arecordlabel/issues/9
some releases have the mp3's in sub-folders, have to improve the tracks crawler to go look in sub-directories aswell. Usually compilations with multiple cds, or the goto80 release which had different directories for the different formats (one in mp3, the other in amiga mod)

**Comment by psenough** [comment]
it's very few cases (only 2 or 3). later releases started being named as 101 102 103 ... 201 202 203 to distinguish multiple cds, instead of different directories.

**Comment by dazld** [comment]
hm.. around here, right? https://github.com/enoughrec/arecordlabel/blob/master/lib/get_audiofilenames.php#L46

**Comment by psenough** [comment]
i'm not sure. need to look at the code properly.
i think i can fix this, just need a couple hours free time next weekend or something.
also not sure if that .php that is on the repo is the latest one that is actually being called to generate the .json, have to check sources of the other phps which are not on the repo for security reasons.

**Comment by psenough** [comment]
also since it's only on 2 or 3 releases, might be easier to just export those manually and put an exception for those specific instead of fiddling with recursiveness or spaghetti code in php.

**Comment by psenough** [comment]
fixed for enrcmp01, request to scene.org pending for enrmp151 (mp3s need to be extracted on server)
